config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'static_pages#home'
  

  
  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
  
  validates :title,
    presence: true
    
  validates :message,
    presence: true
   
  validates :slug_title,
    presence: true,
    uniqueness: true
    
  default_scope -> { order(created_at: :desc )}
  
  before_validation  :set_slug_title
  
  belongs_to :user
  
  private 
    def set_slug_title
      self.title ||= ""
      self.slug_title = self.title.parameterize
    end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :posts
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :authenticate_user!
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def show
    @post = Post.find_by(slug_title: params[:id])
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:success] = "Post created"
      redirect_to root_url
    else
      @posts = Post.all
      render "static_pages/home"
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      flash[:success] = "Post updated"
      redirect_to root_url
    else
       render "posts/edit"
    end
  end

  def destroy
    Post.find(params[:id]).destroy
    flash[:success] = "Post deleted"
    redirect_to request.referrer || root
  end
  
  private 
    def post_params
      params.require(:post).permit(:title, :message, :slug_title)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
    @post = Post.new
    @posts = Post.all
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
   # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Microblog"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
  
end

app/helpers/post_helper.rb
module PostHelper
  
  def post_show_path (post)
    "#{root_url}posts/#{post.slug_title}"
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <p>Developed by Regis</p>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <h1><%= link_to "Microblog", root_url, class: "logo" %>
      <ul class="header_menu">
        <li><%= link_to "Logout 1", "/users/sign_out", method: :delete %><li>
      </ul>
    </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= 
      stylesheet_link_tag "application", 
      media: "all",
      "data-turbolinks-track" => true 
    %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
    
  </body>
</html>

app/views/posts/_form.html.erb
<section class="post_form">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@post) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="field">
          <%= f.label :title %>
          <%= f.text_field :title %>
          
          <%= f.label :message %>
          <%= f.text_area :message %>
        </div>
        <%= f.submit "Post", class: "btn btn-primary" %>
      
      <% end %>
    </div>
  </div>
</section>

app/views/posts/_post.html.erb
<ul class="post">
  <li>
    <span class="post-title"><h3><%= link_to post.title, post_show_path(post) %></h3></span>
    <span class="post-message"><%= post.message %></span></br>
    </br>
    <span>
        <small>
          <%= link_to "delete", post, method: :delete, data: {confirm: "You sure?"} %>
        </small>
        |
        <small>
          <%= link_to "edit", edit_post_path(post) %>
        </small>
    </span>
  </li>
</ul>

app/views/posts/_posts.html.erb
<% if @posts && @posts.any? %>
  <section class="posts row col-md-6 col-md-offset-3">
    <h2>Posts</h2>
    <%= render @posts %>
  </section>
<% end %>

app/views/posts/edit.html.erb
<% provide(:title, "Edit Post") %>

<h1>Edit Post</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@post) do |f| %>
    
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :message %>
      <%= f.text_field :message, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/posts/show.html.erb
<% provide(:title, "Show Post") %>
<div class="post">
    <span class="post-title"><h3><%= @post.title %></h3></span>
    <span class="post-message"><%= @post.message %></span>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<%=render 'posts/form' %>
<%=render 'posts/posts' %>